
GET http://localhost:3000
###

POST http://localhost:3000/songs
Content-Type: application/json

{"title": "Song Title 123",
 "artists": [1],
 "releasedDate":"2022-09-22",
"duration": "02:34",
"lyrics":"This is a song, which is a song, which is a song, which is a song, which is a song"
}
###

GET http://localhost:3000/songs
###
GET http://localhost:3000/songs/1
###
PUT  http://localhost:3000/songs/1
###
DELETE  http://localhost:3000/songs/1


### Create a new Playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{"name": "Feel Good Now",
"songs": [2],
"user": 1
}
