
GET http://localhost:3000
###

POST http://localhost:3000/songs
Content-Type: application/json

{"title": "It's test",
 "artists": [1],
 "releasedDate":"2024-11-22",
"duration": "04:34",
"lyrics":"hello , it's great , it's great , it's great , it's great"
}
###

GET http://localhost:3000/songs
###
GET http://localhost:3000/songs/4
###
PUT  http://localhost:3000/songs/4
Content-Type: application/json

{"title": "It's great 577"}
###
DELETE  http://localhost:3000/songs/5


### Create a new Playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{"name": "Feel Good Now",
"songs": [2],
"user": 1
}
